spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
    hibernate:
#      ddl-auto: create
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5430/news_db
    username: postgres
    password: postgres
    hikari:
      schema: news_schema
      connection-timeout: 1000
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS news_schema


